### PR TITLE
Change the implementation of PromiseXS::Promise::all to that of Promises::collect

### PR DESCRIPTION
**Pull request by AnaTofuZ**
Promises, Perl's Promise implementation, returns an ArrayRef when a non-Promise value is put in the collect.
https://metacpan.org/pod/Promises#collect(-@promises-)

However, Promise::XS returns an error.

Promise::XS is compatible with Promise, so I hope it works the same.

### CODE REVIEW

**Comment by AnaTofuZ** [comment]
@FGasper 
Could you please take a look at it? (and if possible I would like to translate it into XS)

**Comment by FGasper** [comment]
@AnaTofuZ Thank you for the PR.

This _should_ be fine. I find it harder to understand, but its concision and its having been lifted from the older module speak in its favour.

**Comment by FGasper** [comment]
As to implementing in XS … feel free!

**Comment by FGasper** [comment]
The latest release (0.18) includes this update.

Thank you again.

**Pull request merged**
